site_name: My Docs
site_url: https://starfilledsky.github.io/Velo-Docs/
docs_dir: src/
site_dir: docs/
repo_url: https://github.com/StarFilledSky/Velo-Docs



markdown_extensions:
  - attr_list
  - toc:
      permalink: "✿"

plugins:
  - search
  - autorefs
  - document-dates:
      position: bottom 
extra_css:
  - assets/stylesheets/extra.css
  # - assets/stylesheets/code-color.css # I think this is a bit much so i'm not including it

nav:
  # - All.md
  # - Targets.md
  - index.md
  - Classes.md
  - Variables.md


theme:
  favicon: assets/images/favicon.ico
  name: material
  features:
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow

  

  palette:
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
      primary: deep purple
      accent: blue

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

